### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by ghost** [beakable/isometric#5]
This module would be great to have on [npm](https://npmjs.org)! This way people will be able to install your module by doing `npm install isometric`. Just follow these steps:
- make a `package.json` file (you can type `npm init` to generate one from a list of questions)
- pick a name that hasn't been taken (`isometric` is available!)
- figure out where the `main` field in package.json should point

You can read more about publishing browser code to npm here: http://maxogden.com/node-packaged-modules.html

The main field part is a bit tricky since you've got a list of script tags in the example: https://github.com/beakable/isometric/blob/master/Samples/sample1.html#L62-L73
but with a little work you can create a script to concatenate those into a UMD bundle so that consumers of your library will be able to drop in a single script tag to use your library or else just do `var iso = require(''isometric)` if they're using commonjs and won't need to juggle a bunch of globals around.

If you want an example of another game engine published to npm, check out how [voxeljs](http://voxeljs.com/) does it. You can also check out the [game-modules](https://github.com/hughsk/game-modules) repo put together by @hughsk and add isometric to that list once it's up on npm and packaged up.

**Comment by SomethingSexy** [comment]
Hopefully it is OK to post here. At this point I think it would be fantastic if you did post this to npm as well.  npm is used for much more now than just packages that work with node.
