### ISSUE TITLE
update demo

### ISSUE THREAD

**Issue by sielay** [beakable/isometric#9]
Hi

Could you please update demo. You made quite massive changes so far in the engine and basing on current version demo doesn't work. Because complexity and lack of documentation it is quite difficult to find out differences.

**Comment by beakable** [comment]
Will update all of the samples today/tomorrow and drop another comment once done.

Thanks,

Iain

**Comment by beakable** [comment]
https://github.com/anthonymoralez/jsiso-samples/tree/master/public

All Samples updated, all legacy XML map loading removed, as well as the newer promise method for image & json loading implemented.

The original Sample0 requires some fixing but I'll get round to that later. 

Let me know if you run into any issues with these now,

Thanks,

Iain
